#!/usr/bin/env bash
#
# scaffold.sh — deterministic clone + scrub for a new MightyLocal client site.
#
# Copies astro-sites/example-site into astro-client-sites/<slug>, strips every
# build artifact / env file that must never be carried into a fresh repo, and
# writes a clean .dev.vars with the fixed API base + this site's host.
#
# It does NOT edit package.json / wrangler.jsonc / astro.config.mjs — those
# structured edits (package name, Worker name, rental wiring) are done by the
# skill via targeted Edits, because they need judgment. This script is the
# mechanical, idempotent part only.
#
# Usage:  scaffold.sh <slug> <host> <rentals:true|false>
#   slug     kebab-case, e.g. main-hardware-oh  (dir + Worker name + repo name)
#   host     e.g. mainhardwareoh.com            (MIGHTY_SITE_HOST)
#   rentals  true|false                         (adds RENTAL_API_BASE_URL when true)

set -euo pipefail

# --- Fixed constants (same for every site — never prompted) -------------------
MIGHTY_API_BASE_URL="https://mlapi.newmediaretailer.com"
RENTAL_API_BASE_URL="https://rental-api.newmediaretailer.com"

# --- Args ---------------------------------------------------------------------
SLUG="${1:-}"
HOST="${2:-}"
RENTALS="${3:-false}"

if [[ -z "$SLUG" || -z "$HOST" ]]; then
  echo "usage: scaffold.sh <slug> <host> <rentals:true|false>" >&2
  exit 2
fi

if [[ ! "$SLUG" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  echo "error: slug '$SLUG' is not kebab-case (lowercase letters, digits, single hyphens)" >&2
  exit 2
fi

# --- Resolve repo paths from this script's location ---------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# scripts -> new-client-site -> skills -> .claude -> astro-sites
ASTRO_SITES="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
PROJECT_ROOT="$(cd "$ASTRO_SITES/.." && pwd)"
EXAMPLE_SITE="$ASTRO_SITES/example-site"
TARGET="$PROJECT_ROOT/astro-client-sites/$SLUG"

if [[ ! -d "$EXAMPLE_SITE" ]]; then
  echo "error: template not found at $EXAMPLE_SITE" >&2
  exit 1
fi
if [[ -e "$TARGET" ]]; then
  echo "error: target already exists: $TARGET" >&2
  exit 1
fi

# --- 1. Copy the template -----------------------------------------------------
cp -R "$EXAMPLE_SITE" "$TARGET"

# --- 2. Scrub artifacts / env that must not enter a fresh repo ----------------
# node_modules/dist/.astro/.wrangler: build output. worker-configuration.d.ts &
# image-manifest.json: generated. CHANGELOG.md: example-site's own history.
# .dev.vars: env-specific (gitignored) — regenerated below.
( cd "$TARGET" && rm -rf \
    node_modules dist .astro .wrangler \
    worker-configuration.d.ts image-manifest.json CHANGELOG.md .dev.vars )

# --- 3. Write a clean .dev.vars ----------------------------------------------
DEV_VARS="$TARGET/.dev.vars"
{
  echo "# Local dev env for the Cloudflare runtime (read via cloudflare:workers)."
  echo "# Gitignored. Generated by the new-client-site skill."
  echo "MIGHTY_API_BASE_URL=$MIGHTY_API_BASE_URL"
  echo "MIGHTY_SITE_HOST=$HOST"
  if [[ "$RENTALS" == "true" ]]; then
    echo ""
    echo "# Rentals enabled (mightyRental()). Bearer token comes from the Secrets"
    echo "# Store in prod; paste a dev token below if the local rental API needs one."
    echo "RENTAL_API_BASE_URL=$RENTAL_API_BASE_URL"
    echo "# RENTAL_API_TOKEN="
  fi
} > "$DEV_VARS"

# --- 4. Report ----------------------------------------------------------------
echo "scaffolded: $TARGET"
echo "  copied from: $EXAMPLE_SITE"
echo "  scrubbed:    node_modules dist .astro .wrangler worker-configuration.d.ts image-manifest.json CHANGELOG.md"
echo "  wrote:       .dev.vars (MIGHTY_SITE_HOST=$HOST, rentals=$RENTALS)"
echo "TARGET=$TARGET"
